Models/ErrorViewModel.cs
namespace SmartLife_Calculator.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EcologyCalcController.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartLife_Calculator.Controllers
{
    public class EcologyCalcController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FinanceCalcController.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartLife_Calculator.Controllers
{
    public class FinanceCalcController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FitnessCalcController.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartLife_Calculator.Controllers
{
    public class FitnessCalcController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HealthCalcController.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartLife_Calculator.Controllers
{
    public class HealthCalcController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SmartLife_Calculator.Models;
using System.Diagnostics;

namespace SmartLife_Calculator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Calculator()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductivityCalcController.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartLife_Calculator.Controllers
{
    public class ProductivityCalcController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/SecurityCalcController.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartLife_Calculator.Controllers
{
    public class SecurityCalcController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/EcologyCalc/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/FinanceCalc/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/FitnessCalc/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/HealthCalc/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Home/Calculator.cshtml
@{
    ViewData["Title"] = "Calculator";
}
<link href="..\css\calculatorstyle.css" rel="stylesheet" />
<link href="..\lib\font-awesome\css\font-awesome.min.css" rel="stylesheet" />
<h1>@ViewData["Title"]</h1>
<div class="main col-md-6">
    <div class="display"> 
        <button class="dark_mode_btn"><i class="fa fa-moon-o" aria-hidden="true"></i></button> 
        <p id="history"><i class="fa fa-history" aria-hidden="true"></i>&nbsp;History</p>
        <h2 id="result"></h2> 
    </div> 
    <div class="buttons"> 
        <button id="clear">C</button> 
        <button id="delete_single_num"><i class="fa fa-scissors" aria-hidden="true"></i></button> 
        <button id="Normal_btn">/</button> 
        <button id="Normal_btn">*</button>
    </div> 
    <div class="buttons"> 
        <button id="Normal_btn">7</button> 
        <button id="Normal_btn">8</button>
        <button id="Normal_btn">9</button> 
        <button id="Normal_btn">-</button>
    </div> 
    <div class="buttons"> 
        <button id="Normal_btn">4</button> 
        <button id="Normal_btn">5</button> 
        <button id="Normal_btn">6</button> 
        <button id="Normal_btn">+</button> 
    </div> 
    <div class="buttons"> 
        <button id="Normal_btn">1</button> 
        <button id="Normal_btn">2</button>
        <button id="Normal_btn">3</button> 
        <button id="Normal_btn">.</button> 
    </div> 
    <div class="buttons"> 
        <button id="Normal_btn">0</button> 
        <button id="Normal_btn">00</button>
        <button id="equalTo">=</button>
    </div> 
</div> 
<script src="..\js\calculatorscript.js"></script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/ProductivityCalc/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/SecurityCalc/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartLife_Calculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/ecologystyle.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg NavMenu">
            <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="">
                        <a class="nav-link nav-item MenuNavButton " asp-controller="Home" asp-action="Index">🏢</a>
                    </li>
                    <li class="">
                        <a class="nav-link nav-item MenuNavButton NavCalcButton" asp-controller="EcologyCalc" asp-action="Index"> Ecology</a>
                    </li>
                    <li class="">
                        <a class="nav-link nav-item MenuNavButton NavCalcButton" asp-controller="FinanceCalc" asp-action="Index">Finance</a>
                    </li>
                    <li class="">
                        <a class="nav-link nav-item MenuNavButton NavCalcButton" asp-controller="FitnessCalc" asp-action="Index">Fitness</a>
                    </li>
                    <li class="">
                        <a class="nav-link nav-item MenuNavButton NavCalcButton" asp-controller="HealthCalc" asp-action="Index">Health</a>
                    </li>
                    <li class="">
                        <a class="nav-link nav-item MenuNavButton NavCalcButton" asp-controller="ProductivityCalc" asp-action="Index">Productivity</a>
                    </li>
                    <li class="">
                        <a class="nav-link nav-item MenuNavButton NavCalcButton" asp-controller="SecurityCalc" asp-action="Index">Security</a>
                    </li>
                    <li class="">
                        <a class="nav-link nav-item MenuNavButton ">🚕</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SmartLife_Calculator
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>